// Generated by CoffeeScript 1.6.2
(function() {
  enchant();

  window.onload = function() {
    var GAME_X, GAME_Y, game;

    GAME_X = 320;
    GAME_Y = 302;
    game = new Game(GAME_X, GAME_Y);
    game.fps = 15;
    game.preload("chara1.png");
    game.onload = function() {
      var bear, bear2;

      bear = new Sprite(32, 32);
      bear.image = game.assets["chara1.png"];
      bear.x = 0;
      bear.y = 0;
      bear.frame = 5;
      bear.dx = 1;
      game.rootScene.addChild(bear);
      bear.addEventListener("enterframe", function() {
        this.x += this.dx;
        this.frame = this.age % 2 + 6;
        if ((GAME_X - 32 < this.x) || (this.x < 0)) {
          return this.dx *= -1;
        }
      });
      bear.addEventListener("touchstart", function() {
        return game.rootScene.removeChild(bear);
      });
      bear2 = new Sprite(32, 32);
      bear2.image = game.assets["chara1.png"];
      bear2.x = 0;
      bear2.y = 40;
      bear2.frame = 4;
      bear2.dx = 3;
      game.rootScene.addChild(bear2);
      bear2.addEventListener("enterframe", function() {
        this.x += this.dx;
        if ((GAME_X - 32 < this.x) || (this.x < 0)) {
          return this.dx *= -1;
        }
      });
      return bear2.addEventListener("touchstart", function() {
        return game.rootScene.removeChild(bear2);
      });
    };
    return game.start();
  };

}).call(this);
